# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_monitoring_form(object):
    def setupUi(self, monitoring_form):
        monitoring_form.setObjectName("monitoring_form")
        monitoring_form.resize(294, 488)
        self.monitor_tabs = QtWidgets.QTabWidget(monitoring_form)
        self.monitor_tabs.setEnabled(True)
        self.monitor_tabs.setGeometry(QtCore.QRect(10, 10, 281, 391))
        self.monitor_tabs.setToolTipDuration(-3)
        self.monitor_tabs.setObjectName("monitor_tabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.general_table_gest = QtWidgets.QTableWidget(self.tab_3)
        self.general_table_gest.setEnabled(True)
        self.general_table_gest.setGeometry(QtCore.QRect(10, 10, 251, 341))
        self.general_table_gest.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.general_table_gest.setWordWrap(True)
        self.general_table_gest.setRowCount(1)
        self.general_table_gest.setColumnCount(2)
        self.general_table_gest.setObjectName("general_table_gest")
        item = QtWidgets.QTableWidgetItem()
        self.general_table_gest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.general_table_gest.setHorizontalHeaderItem(1, item)
        self.monitor_tabs.addTab(self.tab_3, "")
        self.group_tab = QtWidgets.QWidget()
        self.group_tab.setEnabled(True)
        self.group_tab.setObjectName("group_tab")
        self.group_table = QtWidgets.QTableWidget(self.group_tab)
        self.group_table.setEnabled(True)
        self.group_table.setGeometry(QtCore.QRect(10, 10, 251, 341))
        self.group_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.group_table.setWordWrap(True)
        self.group_table.setRowCount(1)
        self.group_table.setColumnCount(2)
        self.group_table.setObjectName("group_table")
        item = QtWidgets.QTableWidgetItem()
        self.group_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.group_table.setHorizontalHeaderItem(1, item)
        self.monitor_tabs.addTab(self.group_tab, "")
        self.thr_lbl_class_val_2 = QtWidgets.QLabel(monitoring_form)
        self.thr_lbl_class_val_2.setGeometry(QtCore.QRect(250, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.thr_lbl_class_val_2.setFont(font)
        self.thr_lbl_class_val_2.setLineWidth(1)
        self.thr_lbl_class_val_2.setWordWrap(True)
        self.thr_lbl_class_val_2.setObjectName("thr_lbl_class_val_2")
        self.thr_lbl_class_2 = QtWidgets.QLabel(monitoring_form)
        self.thr_lbl_class_2.setGeometry(QtCore.QRect(30, 420, 251, 31))
        self.thr_lbl_class_2.setLineWidth(1)
        self.thr_lbl_class_2.setWordWrap(True)
        self.thr_lbl_class_2.setObjectName("thr_lbl_class_2")
        self.trsh_class_sldr_2 = QtWidgets.QSlider(monitoring_form)
        self.trsh_class_sldr_2.setGeometry(QtCore.QRect(30, 450, 211, 22))
        self.trsh_class_sldr_2.setMinimum(1)
        self.trsh_class_sldr_2.setProperty("value", 27)
        self.trsh_class_sldr_2.setOrientation(QtCore.Qt.Horizontal)
        self.trsh_class_sldr_2.setObjectName("trsh_class_sldr_2")
        self.overall_gest = QtWidgets.QLabel(monitoring_form)
        self.overall_gest.setGeometry(QtCore.QRect(30, 400, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.overall_gest.setFont(font)
        self.overall_gest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overall_gest.setWordWrap(True)
        self.overall_gest.setObjectName("overall_gest")
        self.clear_btn_gest = QtWidgets.QPushButton(monitoring_form)
        self.clear_btn_gest.setGeometry(QtCore.QRect(60, 450, 161, 31))
        self.clear_btn_gest.setObjectName("clear_btn_gest")

        self.retranslateUi(monitoring_form)
        self.monitor_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(monitoring_form)

    def retranslateUi(self, monitoring_form):
        _translate = QtCore.QCoreApplication.translate
        monitoring_form.setWindowTitle(_translate("monitoring_form", "Мониторинг"))
        item = self.general_table_gest.horizontalHeaderItem(0)
        item.setText(_translate("monitoring_form", "Название"))
        item = self.general_table_gest.horizontalHeaderItem(1)
        item.setText(_translate("monitoring_form", "Концентрация"))
        self.monitor_tabs.setTabText(self.monitor_tabs.indexOf(self.tab_3), _translate("monitoring_form", "По жестам"))
        item = self.group_table.horizontalHeaderItem(0)
        item.setText(_translate("monitoring_form", "Название"))
        item = self.group_table.horizontalHeaderItem(1)
        item.setText(_translate("monitoring_form", "Концентрация"))
        self.monitor_tabs.setTabText(self.monitor_tabs.indexOf(self.group_tab), _translate("monitoring_form", "По группам"))
        self.thr_lbl_class_val_2.setText(_translate("monitoring_form", "0.27"))
        self.thr_lbl_class_2.setText(_translate("monitoring_form", "Количество фреймов при котором жест считается распознанным:"))
        self.overall_gest.setText(_translate("monitoring_form", "Всего распознано жестов:"))
        self.clear_btn_gest.setText(_translate("monitoring_form", "Очистка мониторинга"))


